;	CPU  Z80

	.IFNDEF RAMSTARTLOC

	
	DEFINE BOOT;,ALIGN=1; Define a section
	DEFINE IM1INTSEG ;Define a section
	DEFINE NMIIM1INTSEG
	DEFINE CODE;,ALIGN=1

	DEFINE RST08SEG
	DEFINE RST10SEG
	DEFINE RST18SEG
	DEFINE RST20SEG
	DEFINE RST28SEG
	DEFINE RST30SEG
	DEFINE RST38SEG

	DEFINE RST66SEG

	DEFINE INTTABLE, 	ALIGN=256 ; Define a section
	
RAMSTARTLOC equ 04000h
VIDSTARTLOC equ 2400h
FONTSTARTLOC equ	2C00H

SCRLINES	equ		18h
SCRWIDTH	equ		20h


;Z84C15 equ 1 ;Uncomment when building for Z84C15



	.ifdef Z84C15

KIOBASE	equ	10h

CTCIOBASE	equ	00h
SIOIOBASE	equ	18h
PIOIOBASE	equ	1Ch
PIAIOBASE	equ	11B
KIOIOBASE	equ	11B

PIOPORTADATA	equ	00b
PIOPORTACMD		equ	01b
PIOPORTBDATA	equ	10b
PIOPORTBCMD		equ	11b

CTCCHANNEL0		equ	00b
CTCCHANNEL1		equ	01b
CTCCHANNEL2		equ	10b
CTCCHANNEL3		equ	11b

SIOPORTADATA	equ	00b
SIOPORTACMD		equ	01b
SIOPORTBDATA	equ	10b
SIOPORTBCMD		equ	11b

MAKEPORT	MACRO	Name,Base,Device,Register
Name equ Base|(Device<<2)|(Register)
	ENDMAC 

	.else
KIOBASE	equ	0FCh

PIOIOBASE	equ	00B
CTCIOBASE	equ	01B
SIOIOBASE	equ	10B
PIAIOBASE	equ	11B
KIOIOBASE	equ	11B

PIOPORTADATA	equ	00b
PIOPORTACMD		equ	01b
PIOPORTBDATA	equ	10b
PIOPORTBCMD		equ	11b

CTCCHANNEL0		equ	00b
CTCCHANNEL1		equ	01b
CTCCHANNEL2		equ	10b
CTCCHANNEL3		equ	11b

SIOPORTADATA	equ	00b
SIOPORTACMD		equ	01b
SIOPORTBDATA	equ	10b
SIOPORTBCMD		equ	11b

PIAPORTCDATA	equ	00b
PIAPORTCCMD		equ	01b

KIOCOMMANDA		equ	10b
KIOCOMMANDB		equ	11b

MAKEPORT	MACRO	Name,Base,Device,Register
Name equ Base|(Device<<10)|(Register<<8)
	ENDMAC 

	.endif


	MAKEPORT PIOADATA,KIOBASE,PIOIOBASE,PIOPORTADATA
	MAKEPORT PIOACMD,KIOBASE,PIOIOBASE,PIOPORTACMD
	MAKEPORT PIOBDATA,KIOBASE,PIOIOBASE,PIOPORTBDATA
	MAKEPORT PIOBCMD,KIOBASE,PIOIOBASE,PIOPORTBCMD

	MAKEPORT CTCCH0,KIOBASE,CTCIOBASE,CTCCHANNEL0
	MAKEPORT CTCCH1,KIOBASE,CTCIOBASE,CTCCHANNEL1
	MAKEPORT CTCCH2,KIOBASE,CTCIOBASE,CTCCHANNEL2
	MAKEPORT CTCCH3,KIOBASE,CTCIOBASE,CTCCHANNEL3

	MAKEPORT SIOADATA,KIOBASE,SIOIOBASE,SIOPORTADATA
	MAKEPORT SIOACMD,KIOBASE,SIOIOBASE,SIOPORTACMD
	MAKEPORT SIOBDATA,KIOBASE,SIOIOBASE,SIOPORTBDATA
	MAKEPORT SIOBCMD,KIOBASE,SIOIOBASE,SIOPORTBCMD

	.ifdef Z84C15
	.else
	MAKEPORT PIACDATA,KIOBASE,PIAIOBASE,PIAPORTCDATA
	MAKEPORT PIACCMD,KIOBASE,PIAIOBASE,PIAPORTCCMD

	MAKEPORT KIOCMDA,KIOBASE,KIOIOBASE,KIOCOMMANDA
	MAKEPORT KIOCMDB,KIOBASE,KIOIOBASE,KIOCOMMANDB
	.endif
	
WDTMT	equ	0F0h
WDTCR	equ	0F1h

IPR		equ	0F4h

SCRP	equ	0EEh
SCDP	equ	0EFh

SERIALTXBUFFLEN	equ	020h	;must be power of 2

DEFB MACRO P1
	DB P1
	ENDMAC

DEFW MACRO P1
	DW P1
	ENDMAC

DEFM MACRO P1
	DB P1
	ENDMAC

DOOUT	MACRO	ADDR,VALUE
	push 	AF
	push 	BC

	ld a,VALUE	; write into WR0: error reset, select WR0
	.ifdef Z84C15
	out (ADDR),A
	.else
	ld BC,ADDR
	out (BC),A
	.endif

	pop 	BC
	pop 	AF
	
	ENDMAC 

DOIN	MACRO	ADDR,DEST
	push 	AF
	push 	BC

	.ifdef Z84C15
	in a,(ADDR)
	.else
	ld BC,ADDR
	in 	a,(BC)
	.endif

	ld	DEST,a
	pop BC
	POP	AF
	
	ENDMAC 

	.endif

